INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (1,'Ford',2,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (2,'Chevrolet',2,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (3,'Nissan',1,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (4,'Renault',1,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (5,'Fiat',1,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (6,'Volkswagen',1,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (7,'KIA',2,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (8,'Audi',2,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (9, 'BMW',2,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (10,'Dacia',3,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (11,'Honda',3,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (12,'Hyundai',3,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (13,'Jeep',3,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (14,'Mitsubishi',1,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (15,'Peugeot',1,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (16, 'Suzuki',4,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (17,'Volvo',4,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (18, 'Toyota',1,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (19,'Tesla',4,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (20,'Subaru',4,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (21,'Seat',4,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (22,'Mercedes Benz',2,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (23,'Mazda',5,1)
INSERT INTO marcas  (idMarca, descripcion,idPais,idEstado) values (24,'Masseratti',5,1)