INSERT INTO PAISES VALUES (1, ARGENTINA);
INSERT INTO PAISES VALUES (2, BRASIL);
INSERT INTO PAISES VALUES (3, CHILE);
INSERT INTO PAISES VALUES (4, COLOMBIA);
INSERT INTO PAISES VALUES (5, URUGUAY);

