INSERT INTO TIPOS_DOCUMENTOS VALUES (1, 'DNI');
INSERT INTO TIPOS_DOCUMENTOS VALUES (2, 'PASAPORTE');
INSERT INTO TIPOS_DOCUMENTOS VALUES (3, 'LE');
INSERT INTO TIPOS_DOCUMENTOS VALUES (4, 'CI');
INSERT INTO TIPOS_DOCUMENTOS VALUES (5, 'LC');

